### PR TITLE
prescriptive-backend

### PR DESCRIPTION
**Pull request by tsarg88**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Commit 785dc20c0c4880bdc34484df4e28fe52bba763fa, or "Created test db for testing db CRUD action model" doesn't seem to have any notable changes. also- is there a particular need for a CRUD action model in our project?

**Comment by tsarg88** [comment]
> CRUD action model in our pr

That's a great question! I think it would be nice to have, in order to refer on the Endpoints side

**Comment by workingjubilee** [comment]
As it turns out, we do in fact need a mostly-complete CRUD suite for updates as the Python worker cogitates.

**Review by workingjubilee — APPROVED** [review]
Looks good, I did discuss some of the changes but everything seems to be in order.

**Pull request merged**
